/**
 * HUB6.3D — the Analytics Lab: 14 staged Dailies, generated by HUB6.3B's real
 * `GET /api/history/v1` (`d4a43826`), read by the production parser.
 *
 * These tests hold the lab to its provenance (the golden is what the checked-in
 * facts produce), to the scenarios it exists for, and hold the frontend's
 * Free current facts to the server's own definitions.
 */
import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { readHistoryPage, type DailyHistoryRecord, type HistoryStage } from "@/lib/history/contracts";
import { longestStreakOf, stageCurrentFacts } from "@/components/quiz/workspace/historyViewModel";
import { ANALYTICS_LAB_GOLDEN, type AnalyticsLabScenario } from "./analyticsLabSource";
import { analyticsLabInput, ANALYTICS_LAB } from "./analyticsLabInput";
import { ANALYTICS_LAB_FACTS } from "./analyticsLabFacts";
import { TIMMY_HISTORY_GOLDEN } from "./timmyHistorySource";

function records(scenario: AnalyticsLabScenario = "lab_premium"): DailyHistoryRecord[] {
  return ANALYTICS_LAB_GOLDEN.scenarios[scenario].flatMap((p) => readHistoryPage(p).items as DailyHistoryRecord[]);
}
const byRun = (n: number, scenario?: AnalyticsLabScenario) =>
  records(scenario).find((r) => r.runId === `lab-run-${String(n).padStart(2, "0")}`)!;
const stage = (r: DailyHistoryRecord, kind: string) => r.stages.find((s) => s.kind === kind)!;
const status = (s: HistoryStage, metric: string) =>
  s.analytics?.personalFacts.personal?.records.find((x) => x.metric === metric)?.status;

describe("Analytics Lab — provenance", () => {
  it("the golden was generated from exactly the checked-in facts", () => {
    const sha = createHash("sha256").update(analyticsLabInput(), "utf8").digest("hex");
    expect(sha).toBe(ANALYTICS_LAB_GOLDEN.input_sha256);
  });

  it("names the HUB6.3B backend it came from, and stays apart from the HUB2.3 goldens", () => {
    expect(ANALYTICS_LAB_GOLDEN.hub6_3b_commit).toMatch(/^d4a43826/);
    expect(ANALYTICS_LAB_GOLDEN.generated_by).toMatch(/hub63-generate-analytics-lab/);
    // The certified HUB5/HUB6 accounts are untouched: a different input.
    expect(TIMMY_HISTORY_GOLDEN.input_sha256).not.toBe(ANALYTICS_LAB_GOLDEN.input_sha256);
  });

  it("the lab uses the PRODUCTION persistence shape; other accounts do not", () => {
    expect(ANALYTICS_LAB_FACTS.production).toBe(true);
    const rows = ANALYTICS_LAB.rows;
    expect(rows.ranked_rounds?.length).toBeGreaterThan(0);
    const tags = (rows.ranked_rounds ?? []).map((r) => JSON.parse(r.segment_config_json).analytics_tag as string);
    expect(tags.some((t) => t.startsWith("daily_standard_v1:") && t.endsWith(":journey_slice"))).toBe(true);
    expect(tags.some((t) => t.startsWith("daily_review:"))).toBe(true);
    expect(tags.some((t) => t.startsWith("weak_areas:"))).toBe(true);
  });
});

describe("Analytics Lab — the 14 Dailies", () => {
  it("14 staged Dailies across two pages; 4- and 5-stage runs", () => {
    const all = records();
    expect(all).toHaveLength(14);
    expect(ANALYTICS_LAB_GOLDEN.scenarios.lab_premium).toHaveLength(2);
    expect(byRun(1).stages).toHaveLength(4);
    expect(all.filter((r) => r.stages.length === 5)).toHaveLength(13);
  });

  it("production Standard: Splash ×4, Meta Reflex, Splash ×3, Meta Reflex, one five-child Journey", () => {
    const s = stage(byRun(3), "standard");
    expect(s.modules!.map((m) => m.unit)).toEqual([
      "splash", "splash", "splash", "splash", "meta_reflex",
      "splash", "splash", "splash", "meta_reflex", "journey",
    ]);
    expect(s.modules![9].questionsPlayed).toBe(5);
    expect(s.modules![4].questionsPlayed).toBe(5);
    // L14's Journey stopped after four children.
    expect(stage(byRun(14), "standard").modules![9].questionsPlayed).toBe(4);
  });

  it("Time Trial 23 / 29 → 25 / 28: 2 more correct, 1 fewer question played", () => {
    const prev = stage(byRun(3), "time_trial");
    const cur = stage(byRun(4), "time_trial");
    expect([prev.basic.correct, prev.basic.questionsPlayed]).toEqual([23, 29]);
    expect([cur.basic.correct, cur.basic.questionsPlayed]).toEqual([25, 28]);
    const delta = cur.analytics!.personalFacts.personal!.delta!;
    expect(delta.correct).toBe(2);
    expect(delta.questionsPlayed).toBe(-1);
  });

  it("records: first attempt, new, tied and below", () => {
    expect(status(stage(byRun(1), "time_trial"), "correct")).toBe("first_attempt");
    expect(status(stage(byRun(8), "time_trial"), "correct")).toBe("new_record");
    expect(status(stage(byRun(9), "time_trial"), "correct")).toBe("below_record");
    expect(status(stage(byRun(13), "time_trial"), "correct")).toBe("tied_record");
    expect(status(stage(byRun(12), "standard"), "score")).toBe("new_record");
    expect(status(stage(byRun(13), "standard"), "score")).toBe("tied_record");
  });

  it("streak and depth records: TT streak 25, Survival depth 33", () => {
    const tt = stage(byRun(10), "time_trial");
    expect(tt.analytics!.personalFacts.current!.longestStreak).toBe(25);
    expect(status(tt, "longest_streak")).toBe("new_record");
    const surv = stage(byRun(11), "survival");
    expect(surv.analytics!.personalFacts.current!.depth).toBe(33);
    expect(status(surv, "depth")).toBe("new_record");
  });

  it("timeouts are authoritative outcomes: TT ending on the bank, a Survival timeout strike, a Meta Reflex card", () => {
    const l5 = byRun(5);
    expect(stage(l5, "time_trial").basic.timeout).toBe(6);
    expect(stage(l5, "time_trial").questions.at(-1)!.outcome).toBe("timeout");
    const strikes = stage(l5, "survival").analytics!.personalFacts.strikes!;
    expect(strikes.some((s) => s.outcome === "timeout")).toBe(true);
    const reflex = stage(l5, "standard").questions.filter((q) => q.unit === "meta_reflex");
    expect(reflex.some((q) => q.outcome === "timeout")).toBe(true);
  });

  it("Survival: strikes are attributed in order; a completed run used fewer", () => {
    expect(stage(byRun(1), "survival").analytics!.personalFacts.strikes!.map((s) => s.strikeIndex)).toEqual([1, 2, 3]);
    const l10 = stage(byRun(10), "survival");
    expect(l10.analytics!.personalFacts.strikes!.map((s) => s.strikeIndex)).toEqual([1, 2]);
    expect(stageCurrentFacts(l10).strikesUsed).toBe(2);
  });

  it("Review names its sources; the previous Daily notices a different stage set", () => {
    const review = stage(byRun(4), "review");
    const sources = review.analytics!.personalFacts.reviewSources;
    expect(sources).toHaveLength(4);
    for (const s of sources) expect(s.source.runId).toBe("lab-run-04");
    expect(byRun(2).analytics!.personal!.previousDaily!.sameStageKinds).toBe(false);
    expect(byRun(3).analytics!.personal!.previousDaily!.sameStageKinds).toBe(true);
  });

  it("every question carries a public category and a unit", () => {
    for (const r of records()) {
      for (const s of r.stages) {
        for (const q of s.questions) {
          expect(q.publicCategory?.key).toBeTruthy();
          expect(q.unit).toBeTruthy();
        }
      }
    }
  });
});

describe("Analytics Lab — Free current facts equal the server's", () => {
  it("the Free longest streak is the server's on every stage of every run", () => {
    let checked = 0;
    for (const r of records()) {
      for (const s of r.stages) {
        const server = s.analytics?.personalFacts.current?.longestStreak;
        expect(server).not.toBeUndefined();
        expect(longestStreakOf(s)).toBe(server);
        checked++;
      }
    }
    expect(checked).toBe(69);
  });

  it("a Free reader gets the same current facts without Premium analytics", () => {
    const premium = records("lab_premium");
    const free = records("lab_free");
    free.forEach((r, i) => {
      expect(r.analytics).toBeNull();
      r.stages.forEach((s, j) => {
        expect(s.analytics).toBeNull();
        const p = stageCurrentFacts(premium[i].stages[j]);
        const f = stageCurrentFacts(s);
        expect(f.longestStreak).toBe(p.longestStreak);
        expect(f.questionsPlayed).toBe(p.questionsPlayed);
        expect(f.correct).toBe(p.correct);
        if (s.kind === "survival") {
          expect(f.depth).toBe(p.depth);
          expect(f.strikesUsed).toBe(p.strikesUsed);
        }
      });
    });
  });
});
