/**
 * HUB6.3D — the Analytics Lab account, built, and the exact input its golden
 * was generated from (`scripts/hub63-export-analytics-lab-rows.ts` writes it;
 * `scripts/hub63-generate-analytics-lab.py` hashes it into the golden's
 * `input_sha256`, and a test recomputes it).
 *
 * Separate from `timmyHistoryInput` on purpose: the lab is generated by the
 * HUB6.3C backend (`00c794cd`; HUB6.3D used HUB6.3B `d4a43826`), the
 * HUB5/HUB6 accounts by HUB2.3 (`1ffa624c`). Keeping the inputs apart keeps those goldens byte-identical.
 */
import { FIXTURE_ANCHOR } from "./fixtureClock";
import { GOLDEN_PAGE_SIZE } from "./goldenPageSize";
import { buildDailyAccount, canonicalJson, type BuiltDailyAccount } from "./dailyFixtureBuilder";
import { ANALYTICS_LAB_FACTS } from "./analyticsLabFacts";
import { ANALYTICS_LAB_POPULATION_RECIPES } from "./analyticsLabPopulation";

export const ANALYTICS_LAB: BuiltDailyAccount = buildDailyAccount(ANALYTICS_LAB_FACTS);

export function analyticsLabInput(): string {
  return canonicalJson({
    anchor: FIXTURE_ANCHOR,
    page_size: GOLDEN_PAGE_SIZE,
    accounts: { analytics_lab: { user_id: ANALYTICS_LAB_FACTS.userId, rows: ANALYTICS_LAB.rows } },
    // HUB6.3E: the population recipes the generator seeds through HUB6.3C.
    population: ANALYTICS_LAB_POPULATION_RECIPES,
  });
}
