/**
 * Cross-repository contract compatibility (F1.8).
 *
 * `__fixtures__/backend_contract_payloads.json` is generated by the BACKEND
 * (scripts/export_ranked_public_contract_fixtures.py) from the real projection
 * layer — never hand-retyped. This test runs those genuine payloads through
 * the production frontend readers to prove the two repos agree on every
 * versioned contract, and that hidden-field / schema-version tampering is
 * rejected. Regenerate the fixture (and review its diff) when a backend
 * contract changes.
 */
import { describe, expect, it } from "vitest";
import payloads from "./__fixtures__/backend_contract_payloads.json";
import {
  RankedPublicParseError, readMatchResult, readPrivatePlayer, readPublicRound,
  readQueueStatus, readResolvedEnvelope, readResume,
} from "./contracts";

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v));

describe("backend-generated payloads pass the frontend readers", () => {
  it("public_round.v2 with authoritative max_hp", () => {
    const v = readPublicRound(payloads.public_round);
    expect(v.schemaVersion).toBe("ranked_duel.public_round.v2");
    expect(v.players.every((p) => typeof p.maxHp === "number")).toBe(true);
    expect(v.question).not.toBeNull();
    expect(v.presence).not.toBeNull();
  });

  it("private_player.v2 owner-scoped", () => {
    const v = readPrivatePlayer(payloads.private_player);
    expect(v.ownerPlayerId).toBe("userA");
    expect(v.ownAbilities.unlockedAbilityIds.length).toBeGreaterThan(0);
  });

  it("resolved_round.v2 unwraps for the settlement adapter", () => {
    const v = readResolvedEnvelope(payloads.resolved_round);
    expect(v.schemaVersion).toBe("ranked_duel.resolved_round.v2");
    expect(v.payload).toBeTypeOf("object");
  });

  it("resume.v1 nests public/private and no result while active", () => {
    const v = readResume(payloads.resume);
    expect(v.public.schemaVersion).toBe("ranked_duel.public_round.v2");
    expect(v.private.ownerPlayerId).toBe("userA");
    expect(v.result).toBeNull();
  });

  it("queue_status.v1 waiting and matched variants", () => {
    expect(readQueueStatus(payloads.queue_status_waiting).status).toBe("waiting");
    const matched = readQueueStatus(payloads.queue_status_matched);
    expect(matched.status).toBe("matched");
    expect(matched.matchId).toBeTruthy();
  });

  it("match_result.v1 forfeit and no_contest terminal variants", () => {
    expect(readMatchResult(payloads.match_result_forfeit).terminalReason).toBe("forfeit");
    const nc = readMatchResult(payloads.match_result_no_contest);
    expect(nc.terminalReason).toBe("no_contest");
    expect(nc.outcome).toBe("draw");
  });
});

describe("tampered payloads are rejected", () => {
  it("rejects a public payload with an injected correct_index", () => {
    const bad = clone(payloads.public_round);
    (bad.payload as Record<string, unknown>).correct_index = 0;
    expect(() => readPublicRound(bad)).toThrow(RankedPublicParseError);
  });

  it("rejects a private payload with an injected correct_index", () => {
    const bad = clone(payloads.private_player);
    (bad.payload as Record<string, unknown>).correct_index = 2;
    expect(() => readPrivatePlayer(bad)).toThrow(RankedPublicParseError);
  });

  it("rejects a schema-version mismatch", () => {
    const bad = clone(payloads.public_round);
    (bad as Record<string, unknown>).schema_version = "ranked_duel.public_round.v9";
    expect(() => readPublicRound(bad)).toThrow(RankedPublicParseError);
  });

  it("rejects the wrong projection_type", () => {
    const bad = clone(payloads.resolved_round);
    (bad as Record<string, unknown>).projection_type = "public_round";
    expect(() => readResolvedEnvelope(bad)).toThrow(RankedPublicParseError);
  });
});
