// ---------------------------------------------------------------------------
// Academy Updates — the database boundary (WHATSNEW2).
//
// EVERY Supabase call this feature makes is in this file. The public Hall, the
// admin page and their tests all go through the functions below, which means
// the row shape, the ordering rule and the draft guarantee are stated once.
//
// AUTHORIZATION IS NOT HERE. It is in Postgres, as RLS on
// `public.academy_updates`:
//
//   * anyone may SELECT rows where `published = true`;
//   * `has_role(auth.uid(),'admin')` may SELECT everything and may
//     INSERT / UPDATE / DELETE.
//
// So `listPublishedUpdates()` below asks for published rows and Postgres would
// have refused the others regardless — the client filter is a narrowing of a
// permission it already lacks, not the permission itself. Nothing in this
// module consults an `isAdmin` flag, and no service-role key exists in the
// frontend.
//
// TYPING NOTE. `src/integrations/supabase/types.ts` is generated by Lovable
// from the live database, so `academy_updates` does not appear in it until the
// migration has actually been applied. The single cast below is what lets this
// ship before that happens; it is deliberately confined to one place, and the
// hand-written `AcademyUpdateRow` is checked against reality by
// `toAcademyUpdate`, which validates rather than trusts. When Lovable
// regenerates the types the cast becomes redundant and can be dropped without
// touching a caller.
// ---------------------------------------------------------------------------

import { supabase } from "@/integrations/supabase/client";
import type { AcademyUpdate } from "./academy-updates";

/** The table. One name, so a typo is a single-site fix. */
export const ACADEMY_UPDATES_TABLE = "academy_updates";

/** A row exactly as `public.academy_updates` stores it. */
export interface AcademyUpdateRow {
  id: string;
  title: string;
  body: string;
  publish_date: string;
  published: boolean;
  cta_label: string | null;
  cta_href: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

/** Columns the PUBLIC surface reads. Deliberately not `*`: a visitor needs the
 *  notice, not its bookkeeping. */
const PUBLIC_COLUMNS = "id, title, body, publish_date, published, cta_label, cta_href";
/** Columns the ADMIN list reads — the above plus the maintenance timestamps. */
const ADMIN_COLUMNS = `${PUBLIC_COLUMNS}, created_at, updated_at`;

/**
 * `supabase.from` narrowed to this one table, with the generated-types gap
 * bridged once. See the TYPING NOTE above.
 */
function table() {
  return (supabase as unknown as {
    from: (t: string) => {
      select: (columns: string) => {
        order: (
          column: string,
          opts: { ascending: boolean },
        ) => {
          order: (
            column: string,
            opts: { ascending: boolean },
          ) => PromiseLike<{ data: unknown[] | null; error: { message: string } | null }>;
        };
        eq: (column: string, value: unknown) => {
          order: (
            column: string,
            opts: { ascending: boolean },
          ) => {
            order: (
              column: string,
              opts: { ascending: boolean },
            ) => PromiseLike<{ data: unknown[] | null; error: { message: string } | null }>;
          };
        };
      };
      insert: (row: Record<string, unknown>) => PromiseLike<{ error: { message: string } | null }>;
      update: (patch: Record<string, unknown>) => {
        eq: (column: string, value: unknown) => PromiseLike<{ error: { message: string } | null }>;
      };
      delete: () => {
        eq: (column: string, value: unknown) => PromiseLike<{ error: { message: string } | null }>;
      };
    };
  }).from(ACADEMY_UPDATES_TABLE);
}

/**
 * Turn one database row into the `AcademyUpdate` the presentation already
 * understands, or `null` if it is not a usable notice.
 *
 * This VALIDATES rather than casts. A row arriving without a string id or with
 * a non-boolean `published` is not a notice the Hall can safely render — the id
 * is what the browser stores as "seen", and `published` is the draft guarantee
 * restated client-side — so it is dropped. Failing closed on one bad row costs
 * that notice; trusting it could re-announce everything or leak a draft.
 *
 * A CTA survives only if BOTH halves are present and non-empty. Whether the
 * href is a permissible destination is `resolveUpdateCta`'s decision, made at
 * render time on the shared rule; this step only assembles the pair.
 */
export function toAcademyUpdate(row: unknown): AcademyUpdate | null {
  if (!row || typeof row !== "object") return null;
  const r = row as Partial<AcademyUpdateRow>;
  if (typeof r.id !== "string" || !r.id) return null;
  if (typeof r.published !== "boolean") return null;

  const label = typeof r.cta_label === "string" ? r.cta_label.trim() : "";
  const href = typeof r.cta_href === "string" ? r.cta_href.trim() : "";

  return {
    id: r.id,
    date: typeof r.publish_date === "string" ? r.publish_date : "",
    title: typeof r.title === "string" ? r.title : "",
    body: typeof r.body === "string" ? r.body : "",
    published: r.published,
    ...(label && href ? { cta: { label, href } } : {}),
  };
}

/** Map a set of rows, discarding the ones that did not survive validation. */
export function toAcademyUpdates(rows: unknown[] | null | undefined): AcademyUpdate[] {
  if (!Array.isArray(rows)) return [];
  return rows.map(toAcademyUpdate).filter((u): u is AcademyUpdate => u !== null);
}

/**
 * A read that is already on the wire, if there is one.
 *
 * The Hall mounts this feature TWICE — the desktop mark and the mobile row are
 * separate mounts, one of which is hidden at any given width — so without this
 * every enabled Hall load made two identical requests. Callers in the same tick
 * share one promise, which is cleared the moment it settles: this is
 * request coalescing, not a cache, so a later visit still reads fresh rows and
 * a failed read is never remembered as an answer.
 */
let inFlight: Promise<AcademyUpdate[]> | null = null;

/**
 * The PUBLIC read: published notices, newest first.
 *
 * Never throws and never rejects. Academy Updates is optional secondary content
 * on a page whose primary job is the four volumes, so every failure — network,
 * RLS, an unapplied migration, a malformed payload — resolves to an empty list,
 * which the surface treats identically to "the feature is off". A broken read
 * must cost a badge, never the Hall.
 */
export function listPublishedUpdates(): Promise<AcademyUpdate[]> {
  if (inFlight) return inFlight;
  inFlight = fetchPublishedUpdates().finally(() => {
    inFlight = null;
  });
  return inFlight;
}

async function fetchPublishedUpdates(): Promise<AcademyUpdate[]> {
  try {
    const { data, error } = await table()
      .select(PUBLIC_COLUMNS)
      .eq("published", true)
      // publish_date is the owner's ordering; created_at breaks ties in the
      // order the notices were actually written, so two notices dated the same
      // day appear newest-first rather than arbitrarily.
      .order("publish_date", { ascending: false })
      .order("created_at", { ascending: false });
    if (error) return [];
    return toAcademyUpdates(data);
  } catch {
    return [];
  }
}

/**
 * The ADMIN read: every notice, drafts included, newest first.
 *
 * Unlike the public read this one REPORTS its failure, because an admin looking
 * at an empty list needs to know whether that means "nothing written yet" or
 * "the read failed" — those demand opposite responses.
 */
export async function listAllUpdatesForAdmin(): Promise<{
  rows: AcademyUpdateRow[];
  error: string | null;
}> {
  try {
    const { data, error } = await table()
      .select(ADMIN_COLUMNS)
      .order("publish_date", { ascending: false })
      .order("created_at", { ascending: false });
    if (error) return { rows: [], error: error.message };
    return { rows: (Array.isArray(data) ? data : []) as AcademyUpdateRow[], error: null };
  } catch (e) {
    return { rows: [], error: e instanceof Error ? e.message : "Could not load Academy Updates." };
  }
}

/** The editable half of a notice. `id`, timestamps and nothing else are the
 *  database's to set. */
export interface AcademyUpdateDraftInput {
  title: string;
  body: string;
  publish_date: string;
  cta_label: string | null;
  cta_href: string | null;
}

/**
 * Create a notice. Always as a DRAFT — publishing is a separate, deliberate act
 * on a row that already exists and can be read back, so nothing reaches the
 * Hall on the same click that created it.
 */
export async function createUpdate(
  input: AcademyUpdateDraftInput,
): Promise<{ error: string | null }> {
  const { error } = await table().insert({ ...input, published: false });
  return { error: error ? error.message : null };
}

/** Save an edit. `published` is untouched here: editing never changes
 *  visibility, and visibility never rewrites content. */
export async function updateUpdate(
  id: string,
  input: AcademyUpdateDraftInput,
): Promise<{ error: string | null }> {
  const { error } = await table().update({ ...input }).eq("id", id);
  return { error: error ? error.message : null };
}

/**
 * Publish or withdraw one notice.
 *
 * The id is NOT touched, which is the whole reason a correction is not an
 * announcement: browsers remember the newest published id, so a row that keeps
 * its id keeps its "already read" status.
 */
export async function setUpdatePublished(
  id: string,
  published: boolean,
): Promise<{ error: string | null }> {
  const { error } = await table().update({ published }).eq("id", id);
  return { error: error ? error.message : null };
}

/** Delete a notice permanently. Confirmed in the UI before it is called. */
export async function deleteUpdate(id: string): Promise<{ error: string | null }> {
  const { error } = await table().delete().eq("id", id);
  return { error: error ? error.message : null };
}

/**
 * Read the master switch straight from `app_settings`.
 *
 * The public Hall does NOT use this — it reads the switch out of the policy
 * object `useAppSettings()` already fetches. This exists for the admin page,
 * which must show the switch's true current state on load and cannot infer it
 * from a cache.
 *
 * Fails CLOSED: an unreadable row reports `false`, so the admin page never
 * claims a feature is live when it cannot prove it.
 */
export async function readAcademyUpdatesEnabled(
  key: string,
): Promise<{ enabled: boolean; error: string | null }> {
  try {
    const { data, error } = await supabase
      .from("app_settings")
      .select("value")
      .eq("key", key)
      .maybeSingle();
    if (error) return { enabled: false, error: error.message };
    const value = data?.value;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      const enabled = (value as Record<string, unknown>).enabled;
      if (typeof enabled === "boolean") return { enabled, error: null };
    }
    // A missing row is not an error: the migration seeds it, but a database
    // that has not been migrated yet is simply a database where the feature is
    // off, which is the honest reading.
    return { enabled: false, error: null };
  } catch (e) {
    return { enabled: false, error: e instanceof Error ? e.message : "Could not read the switch." };
  }
}

/** Write the master switch. Admin-only, enforced by app_settings' RLS. */
export async function writeAcademyUpdatesEnabled(
  key: string,
  enabled: boolean,
): Promise<{ error: string | null }> {
  const { error } = await supabase
    .from("app_settings")
    .upsert({ key, value: { enabled } });
  return { error: error ? error.message : null };
}
