import { useEffect, useMemo, useState } from "react";
import { BookOpen, Database, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { fetchAtlas, fetchAtlasPreview, type AtlasFamily, type AtlasPayload, type AtlasPreview } from "@/lib/content-atlas/api";

const ANY = "__any__";
const words = (text: string) => text.split("_").join(" ");
const value = (count: { value: number | null; status: string }) => count.status === "UNKNOWN" || count.value == null ? "UNKNOWN" : count.value.toLocaleString();
const yesNo = (v: unknown) => v == null ? "UNKNOWN" : v ? "YES" : "NO";

function Supply({ family, help }: { family: AtlasFamily; help: Record<string, string> }) {
  return <div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{Object.entries(family.supply).map(([key, count]) =>
    <div key={key} title={help[key]} className="rounded-md border border-border/70 bg-muted/30 p-3">
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{words(key)}</div>
      <div className="mt-1 font-mono text-lg font-semibold">{value(count)}</div><div className="text-[10px] text-muted-foreground">{count.method}</div>
    </div>)}</div>;
}

function Candidate({ item }: { item: Record<string, unknown> }) {
  return <article className="rounded-lg border bg-card p-4">
    <div className="mb-2 flex flex-wrap gap-2 text-xs"><Badge variant="outline">{String(item.semantic_ref)}</Badge><Badge variant="secondary">difficulty {String(item.difficulty)}</Badge></div>
    <p className="text-base font-medium">{String(item.prompt)}</p>
    {Array.isArray(item.options) && <div className="my-3 grid gap-1 sm:grid-cols-2">{item.options.map((option, i) => <div key={i} className="rounded border px-3 py-2 text-sm">{String(option)}</div>)}</div>}
    <p className="text-sm"><span className="text-muted-foreground">Correct answer:</span> <strong>{typeof item.correct_answer === "string" ? item.correct_answer : JSON.stringify(item.correct_answer)}</strong></p>
    <details className="mt-3 text-xs text-muted-foreground"><summary className="cursor-pointer">Inputs & provenance</summary><pre className="mt-2 max-h-48 overflow-auto rounded bg-muted p-2 whitespace-pre-wrap">{JSON.stringify({ subject:item.subject, inputs:item.inputs, media:item.media, source:item.source, provenance:item.provenance }, null, 2)}</pre></details>
  </article>;
}

function Detail({ family, atlas, close }: { family: AtlasFamily; atlas: AtlasPayload; close: () => void }) {
  const [preview, setPreview] = useState<AtlasPreview | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [subject, setSubject] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setPreview(await fetchAtlasPreview(family.family_id, Date.now(), subject)); } catch (e) { setError(e instanceof Error ? e.message : "Preview failed"); } finally { setLoading(false); } };
  const lineage = [...family.canonical_sources, family.capability.name, family.source_code ?? family.construction, family.family_id, family.shape.kind, family.serving_authority?.kind ?? "No current Ranked authority", "semantic ref / Review"];
  return <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm"><div className="absolute inset-y-0 right-0 w-full max-w-4xl overflow-y-auto border-l bg-background shadow-2xl">
    <div className="sticky top-0 z-10 flex items-start justify-between border-b bg-background/95 p-5"><div><div className="flex flex-wrap gap-2"><Badge>{family.readiness}</Badge><Badge variant="outline">{family.shape.kind}</Badge><Badge variant="outline">{family.generated ? "Generated" : "Authored/static"}</Badge></div><h2 className="mt-2 text-2xl font-semibold">{family.display_name}</h2><code className="text-xs text-muted-foreground">{family.family_id}</code></div><Button variant="ghost" size="icon" onClick={close}><X /></Button></div>
    <div className="space-y-6 p-5">
      <p>{family.description}</p><Supply family={family} help={atlas.count_help} />
      <section><h3 className="mb-3 font-semibold">Lineage</h3><div className="flex flex-wrap items-center gap-2">{lineage.map((step, i) => <span key={`${step}-${i}`} className="contents"><span className="rounded border bg-muted/30 px-2 py-1 text-xs">{step}</span>{i < lineage.length-1 && <span className="text-muted-foreground">→</span>}</span>)}</div></section>
      <section className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border p-4"><h3 className="font-semibold">Authority & construction</h3><dl className="mt-3 grid grid-cols-[9rem_1fr] gap-2 text-sm"><dt className="text-muted-foreground">Semantic target</dt><dd>{family.semantic_target}</dd><dt className="text-muted-foreground">Capability</dt><dd>{family.capability.name}</dd><dt className="text-muted-foreground">Sources</dt><dd>{family.canonical_sources.join(", ")}</dd><dt className="text-muted-foreground">Construction</dt><dd>{family.construction}</dd><dt className="text-muted-foreground">Code</dt><dd><code>{family.source_code ?? "UNKNOWN"}</code></dd><dt className="text-muted-foreground">Inputs</dt><dd>{family.input_dimensions.join(", ") || "none"}</dd><dt className="text-muted-foreground">Semantic ref</dt><dd><code>{family.semantic_ref_format}</code></dd><dt className="text-muted-foreground">Owner</dt><dd>{family.ownership}</dd></dl></div>
      <div className="rounded-lg border p-4"><h3 className="font-semibold">Hosts & reconstruction</h3><div className="mt-3 grid grid-cols-2 gap-2 text-sm">{["standard","time_trial_suitable","time_trial_reachable","survival","practice","ranked","quiz_forge"].map(k => <div key={k} className="flex justify-between gap-2 border-b py-1"><span>{words(k)}</span><strong>{yesNo(family.hosts[k])}</strong></div>)}</div><p className="mt-3 text-xs text-muted-foreground">{String(family.hosts.time_trial_note)}</p><p className="mt-3 text-sm"><strong>Review:</strong> {family.review}</p><p className="mt-2 text-sm"><strong>Weak Areas:</strong> {family.weak_areas}</p></div></section>
      {family.blockers.length > 0 && <section className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-4"><h3 className="font-semibold text-amber-600">Blockers / reachability notes</h3><ul className="mt-2 list-disc pl-5 text-sm">{family.blockers.map(b => <li key={b}>{b}</li>)}</ul></section>}
      <section><div className="mb-3 flex flex-wrap items-end gap-2"><div className="min-w-52 flex-1"><label className="mb-1 block text-xs text-muted-foreground">Optional subject filter (for example Ahri)</label><Input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject" /></div><Button onClick={load} disabled={loading || !family.preview.supported}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`} />{preview ? "Refresh / reseed" : "Show real examples"}</Button></div>
      {!family.preview.supported && <p className="rounded border p-3 text-sm text-muted-foreground">Preview unavailable: {family.preview.limitations ?? "held, retired, or historical family"}</p>}{error && <p className="text-sm text-destructive">{error}</p>}{preview?.reason && <p className="text-sm text-muted-foreground">{preview.reason}</p>}<div className="grid gap-3">{preview?.candidates?.map((c,i)=><Candidate key={`${String(c.semantic_ref)}-${i}`} item={c}/>)}</div></section>
    </div></div></div>;
}

export default function ContentAtlasPage() {
  const [atlas,setAtlas]=useState<AtlasPayload|null>(null), [error,setError]=useState(""), [selected,setSelected]=useState<AtlasFamily|null>(null);
  const [search,setSearch]=useState(""), [domain,setDomain]=useState(ANY), [readiness,setReadiness]=useState(ANY), [construction,setConstruction]=useState(ANY), [shape,setShape]=useState(ANY), [reach,setReach]=useState(ANY), [tt,setTt]=useState(ANY), [capability,setCapability]=useState(ANY);
  useEffect(()=>{ fetchAtlas().then(setAtlas).catch(e=>setError(e instanceof Error?e.message:"Could not load Atlas")); },[]);
  const families=useMemo(()=>atlas?.families.filter(f=>{ const q=search.toLowerCase(); return (!q || JSON.stringify([f.family_id,f.display_name,f.description,f.canonical_sources,f.capability.name]).toLowerCase().includes(q)) && (domain===ANY||f.domain===domain) && (readiness===ANY||f.readiness===readiness) && (construction===ANY||f.construction===construction) && (shape===ANY||f.shape.kind===shape) && (capability===ANY||f.capability.id===capability) && (reach===ANY||(reach==="reachable")===Boolean(f.serving_authority)) && (tt===ANY||(tt==="suitable")===Boolean(f.hosts.time_trial_suitable)); })??[],[atlas,search,domain,readiness,construction,shape,reach,tt,capability]);
  if(error) return <div className="p-8"><h1 className="text-2xl font-semibold">Content Atlas</h1><p className="mt-4 text-destructive">{error}</p></div>;
  if(!atlas) return <div className="p-8 text-muted-foreground">Loading Content Atlas…</div>;
  const options=(key:"domain"|"readiness"|"construction")=>[...new Set(atlas.families.map(f=>String(f[key])))].sort();
  return <div className="mx-auto max-w-[1600px] space-y-5 p-4 md:p-7"><header className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[.2em] text-muted-foreground"><ShieldCheck className="h-4 w-4"/>Read-only owner tool</div><h1 className="mt-1 text-3xl font-semibold">Content Atlas</h1><p className="text-muted-foreground">What Mogzy knows, how it becomes a question, and where it can actually travel.</p></div><Badge variant="outline">{atlas.schema_version} · {new Date(atlas.generated_at).toLocaleString()}</Badge></header>
  <div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{Object.entries(atlas.overview).map(([k,v])=><div key={k} className="rounded-lg border bg-card p-3"><div className="text-2xl font-semibold">{v}</div><div className="text-[11px] text-muted-foreground">{words(k)}</div></div>)}</div>
  <div className="rounded-lg border bg-card p-4"><div className="grid gap-2 md:grid-cols-4 xl:grid-cols-8"><div className="relative md:col-span-2"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Family, source, capability…"/></div>
  {[[domain,setDomain,"Domain",options("domain")],[capability,setCapability,"Capability",atlas.capabilities.map(c=>c.id)],[construction,setConstruction,"Construction",options("construction")],[readiness,setReadiness,"Readiness",options("readiness")],[shape,setShape,"Shape",["Splash","Slice","Sprint"]],[reach,setReach,"Reachability",["reachable","blocked"]],[tt,setTt,"Time Trial",["suitable","unsuitable"]]] .map(([v,set,label,items])=><Select key={String(label)} value={v as string} onValueChange={set as (x:string)=>void}><SelectTrigger><SelectValue placeholder={String(label)}/></SelectTrigger><SelectContent><SelectItem value={ANY}>Any {String(label).toLowerCase()}</SelectItem>{(items as string[]).map(x=><SelectItem key={x} value={x}>{words(x)}</SelectItem>)}</SelectContent></Select>)}</div></div>
  <div className="grid gap-5 xl:grid-cols-[1fr_20rem]"><section><div className="mb-2 text-sm text-muted-foreground">Showing {families.length} of {atlas.families.length} families</div><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-muted/60 text-xs uppercase text-muted-foreground"><tr><th className="p-3">Family</th><th>Domain / capability</th><th>Construction</th><th>Shape</th><th>Readiness</th><th>Implemented</th><th>Reachable</th><th>TT suitable / reachable</th></tr></thead><tbody>{families.map(f=><tr key={f.family_id} onClick={()=>setSelected(f)} className="cursor-pointer border-t hover:bg-muted/40"><td className="p-3"><div className="font-medium">{f.display_name}</div><code className="text-[11px] text-muted-foreground">{f.family_id}</code></td><td><div>{f.domain}</div><div className="text-xs text-muted-foreground">{f.capability.name}</div></td><td>{f.construction}</td><td>{f.shape.kind}</td><td><Badge variant="outline">{f.readiness}</Badge></td><td>{value(f.supply.implemented)}</td><td>{value(f.supply.authority_reachable)}</td><td>{yesNo(f.hosts.time_trial_suitable)} / {yesNo(f.hosts.time_trial_reachable)}</td></tr>)}</tbody></table></div></section>
  <aside className="space-y-3"><div className="rounded-lg border p-4"><h2 className="flex items-center gap-2 font-semibold"><Database className="h-4 w-4"/>Capability view</h2>{atlas.capabilities.map(c=><button key={c.id} onClick={()=>setCapability(c.id)} className="mt-3 block w-full rounded border p-3 text-left hover:bg-muted"><div className="font-medium">{c.name}</div><div className="text-xs text-muted-foreground">{c.family_ids.length} families · {c.sources.length} sources</div></button>)}</div><div className="rounded-lg border p-4"><h2 className="flex items-center gap-2 font-semibold"><BookOpen className="h-4 w-4"/>Slices & Sprints</h2>{atlas.complex_systems.map(s=><div key={s.id} className="mt-3 border-t pt-3"><div className="flex justify-between"><strong>{s.id}</strong><Badge variant="secondary">{s.shape}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{s.preview}: {s.reason}</p></div>)}</div></aside></div>{selected&&<Detail family={selected} atlas={atlas} close={()=>setSelected(null)}/>}</div>;
}
